### ISSUE TITLE
Add a new seconds_dispatcher argument to the client class and controller helpers

### ISSUE THREAD

**Issue by wlandau** [wlandau/crew#109]
## Prework

* [x] Read and agree to the [Contributor Code of Conduct](https://github.com/wlandau/crew/blob/main/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/ropensci/crew/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/ropensci/crew/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.
* [x] Format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Proposal

c.f. https://github.com/shikokuchuo/mirai/issues/69, avoids dispatcher timeout issues e.g. with large `renv` libraries.

**Comment by shikokuchuo** [comment]
This is no longer required and may be closed as we solved this using `--vanilla` flags for dispatcher. The  'dispatcher' argument is completely reverted in shikokuchuo/mirai@7e6658b
