### ISSUE TITLE
Ominous warning in documentation

### ISSUE THREAD

**Issue by Kodiologist** [wlandau/crew#116]
## Description

Quoth https://wlandau.github.io/crew/:

> The `crew` package has unavoidable risk. It is your responsibility as the user to safely use `crew`. Please read the final clause of the [software license](https://wlandau.github.io/crew/LICENSE.html).

The clause in question is just the usual no-warranty clause in free-software licenses. No further explanation of the "unavoidable risk" or safety issue is provided. I think this is a copypaste that got separated from its original context in 8b0d3c03b5e7a7bc7166105a9ee1b5d8caf2618b, which was a warning about runaway worker processes.

**Comment by wlandau** [comment]
The sections just below that paragraph describe specific known risks, from network security to zombie processes. Hopefully the change in https://github.com/wlandau/crew/commit/6c27d1161685b0e195f67cbe53ae32d4984b76db makes this clearer.

**Comment by Kodiologist** [comment]
Ah, that makes sense, thanks. The font-size change on my browser for the different headers is very subtle, and it wasn't clear that the next header was a subsection of "Risks".
