### ISSUE TITLE
Verbose dispatcher error message

### ISSUE THREAD

**Issue by shikokuchuo** [wlandau/crew#150]
## Prework

* [x] Read and agree to the [Contributor Code of Conduct](https://github.com/wlandau/crew/blob/main/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/wlandau/crew/blob/main/CONTRIBUTING.md).

## Description

In commit 9b69ff7 you try to offer more help to end users.

Whilst I think the out of memory possibility is good to highlight, the following does not apply to dispatcher, and potentially causes more confusion.

    "If that does not help, the {mirai} dispatcher process may have trouble",
    "starting, either because it cannot find R or the R package library,",
    "or because there is something strange about your file system or",
    ".Rprofile/.Renviron files, or you have an {renv} project that",
    "takes a long time to start. Please make sure R sessions can start",
    "quickly in your project. For example, for {renv}, try setting",
    "RENV_CONFIG_SANDBOX_ENABLED=false and",
    "RENV_CONFIG_SYNCHRONIZED_CHECK=false in your .Renviron file",
    "in to speed up {renv} project initialization.\n\n",

The libpaths are passed explicitly to dispatcher and the startup files are not processed due to the `--vanilla` flags.

**Comment by wlandau** [comment]
Right, thanks for reminding me. Removed in 4121838a9dc135ebe8b2dd57e0fb5110323f4ce5.
