### ISSUE TITLE
Do the required arguments include "name"?

### ISSUE THREAD

**Issue by billdenney** [wlandau/crew#160]
This line has 4 required arguments, but the bulleted list below has 5 arguments, including `name`:

https://github.com/wlandau/crew/blob/c572f2236aba73fc469f755da88c33c384a5e52c/vignettes/plugins.Rmd#L80

Is the `name` argument required?  If not, it may help to make that explicit by adding "(optional)" in the bulleted list, or if it is required, it would help to include it on the above line.

(I'm working on an ssh launcher now.)

**Comment by wlandau** [comment]
> Is the name argument required? 

Yes, but this argument and others like it are automatically supplied to `launch_worker()` via the core `launch()` method. In other words, plugin developers don't have a reason to call `launch_worker()` manually, the call is already performed in methods that the plugin developer is not responsible for.

> (I'm working on an ssh launcher now.)

Neat. One thing I have had trouble wrapping my head around is how to establish an SSH connection in the context of `crew`. In `crew`, the worker initiates the connection to the client, whereas I think SSH usually expects this to happen the other way around. At least that's how I have seen it and how I think it currently works in `mirai` (backend of `crew`).
