### ISSUE TITLE
set retry = TRUE in mirai::dispatcher()

### ISSUE THREAD

**Issue by wlandau** [wlandau/crew#170]
c.f. https://github.com/wlandau/crew/discussions/169, https://github.com/shikokuchuo/mirai/issues/117. Implement in `crew` after the next `mirai` release is out.

**Comment by shikokuchuo** [comment]
It seems likely the default will be switched for the next `mirai` release, so do go ahead and set this.

This is all towards ensuring consistent behaviour across dispatcher / non-dispatcher contexts as we move ever closer to threaded dispatcher.

**Comment by wlandau** [comment]
Done. Will resubmit to CRAN on June 26.
