### ISSUE TITLE
Crew worker hook

### ISSUE THREAD

**Issue by multimeric** [wlandau/crew#184]
## Prework

* [x] Read and agree to the [Contributor Code of Conduct](https://github.com/wlandau/crew/blob/main/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/wlandau/crew/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/wlandau/crew/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.
* [x] Format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Proposal

Frequently I want the ability to monitor crew workers, for example by running `strace`. However, crew doesn't seem to provide a hook for doing this.

I propose a new argument to the controller functions such as `crew_controller_local()` called something like `worker_hook`, which is a function that takes the `processx` [`process`](https://processx.r-lib.org/reference/process.html) object. The hook would run as part of the worker initialisation. This would allow me to set up appropriate monitoring. 

For example:
```R
controller <- crew_controller_local(
    worker_hook = function(process){
        pid <- process$get_pid()
        system2("strace", c("-p", pid), stdout="strace_log.txt")
    }
)
```

**Comment by wlandau** [comment]
Sorry, I feel this level of flexibility is not usually going to be necessary for most use cases. You can get the `processx` handles from `controller$launcher$workers$handle`.

**Comment by snowpong** [comment]
If you just want to strace whatever is currently running you can go:

```
monitor <- crew::crew_monitor_local()
monitor$workers()
```

Which spits out the PIDs of the workers, and then you can `sudo strace -p PID`.
Might be useful for people debugging.

**Comment by multimeric** [comment]
From memory, the issue was that I was using the slurm launcher, meaning that the workers were on different machines from the targets master process. It might have been possible to find their PIDs (?), but very difficult to `strace` on a remote node.

**Comment by snowpong** [comment]
Ah, I was thinking for local workers.
