### ISSUE TITLE
`mirai` backend

### ISSUE THREAD

**Issue by wlandau** [wlandau/crew#26]
As a potential non-Redis alternative to #21: https://github.com/shikokuchuo/mirai/discussions/18

**Comment by wlandau** [comment]
To-do list:

* [ ] Test the new code in https://github.com/wlandau/crew/tree/26.
* [ ] Implement a local `callr` process launcher
* [ ] #27
* [ ] #28.
* [ ] Implement launchers for traditional cloud platforms like SGE.

**Comment by wlandau** [comment]
As I explain at https://github.com/shikokuchuo/mirai/discussions/26#discussioncomment-5154149, I am having trouble finding a path forward at the moment.

**Comment by wlandau** [comment]
From my perspective, I think it makes sense to implement a `mirai` backend based on the passive queue, with room in the package for `rrq`/Redis as an alternative. If we find a solution that uses a `mirai`/NNG active queue in the meantime, all the better, but I would prefer to move `crew` forward as far as I can given what I know now.

**Comment by wlandau** [comment]
Recent developments make the active queue much nicer. Autoscaling is going to be easy. Trying to find a workaround with the port situation: https://github.com/shikokuchuo/mirai/discussions/31

**Comment by wlandau** [comment]
The GitHub Actions checks don't indicate this because they have trouble installing `nanonext`, but the implementation of the local `callr` task queue is going well so far. I implemented `R6` classes for launching the `mirai` client and servers, and I like the design. To do:

* [ ] A controller object that creates and manages the "router" object (for the `mirai` client) and the "launcher" object (for launching and monitoring `mirai` servers). At this stage, I think I can solve #28. When a task is pushed to the queue, `crew` could make a decision to either add just one new worker or however many workers would equal the number of tasks. (With, of course, an upper cap on the number of simultaneous workers.)
* [ ] A sort-of "multi-controller" for managing heterogeneous controllers. (Workers are the same within controller but differ from controller to controller.) This is how I want to handle https://github.com/wlandau/crew/discussions/23 in a flexible/general way. (Workers can be heterogeneous not only with respect to resources like GPUs, but also options like max idle time.
* [ ] Load test.
* [ ] Document.

This is all for the local process task queue (the `callr` backend). Before moving on to e.g. SGE or AWS, I want to switch back to `rrq` and see what the analogous prototype would look like.

**Comment by wlandau** [comment]
Implemented with `callr` workers. Not sure about SLURM etc. because of the issue with ports, but AWS should be fine once I figure that out.

**Comment by nviets** [comment]
I'm not familiar with callr. tar_make_clustermq workers with SLURM are convenient because they can be resource restricted via cgroups. Will the same be possible with callr? What's the challenge with SLURM workers?

**Comment by wlandau** [comment]
`callr` is a package for submitting local R processes in a platform-independent way. The `callr` backend allows `crew` to ask as a local multi-process task queue. It is one of many alternatives that will become possible with `crew`, and one of those alternatives will be SLURM. But `callr` is by far the easiest to develop, and there are tricky issues such as #31 that I need to work out before tackling SLURM.

And before that I will be using SGE because that is the cluster I can access. But SLURM should be possible to set up in a Debian VM. I have done it before.

**Comment by nviets** [comment]
Thanks for the detail. I'll be happy to test on SLURM when you get around to it.
