### ISSUE TITLE
CI testing failures

### ISSUE THREAD

**Issue by wlandau** [wlandau/crew#48]
I'm not sure why, but it looks `crew` cannot start the `mirai` client: https://github.com/wlandau/crew/actions/runs/4439129281/jobs/7791146142. If this continues, I think I will need to get in there with [`tmate`](https://mxschmitt.github.io/action-tmate/) to diagnose it.

**Comment by shikokuchuo** [comment]
I don't specifically install system libmbedtls-dev in my workflow, but the version in Ubuntu should be fine. Perhaps get rid of redis-server though you don't need that any more!

This is what I propose to debug this as clearly the dispatcher process isn't alive.

```r
library(mirai)
daemons(url = "abstract://nano")
```
then tmux into another terminal
```r
Rscript -e 'mirai::dispatcher(client="abstract://nano",url="ws://10.1.0.126:56789")'
```
You should then be able to see the error message assuming it errors.

If on the other hand it doesn't then you should be able to query the connection back in your first process, and it gets curioser...

**Comment by wlandau** [comment]
Curioser indeed. I tried that test, and I am still getting timeouts in `daemons()` even though the dispatcher is alive.

```r
> library(mirai)
> daemons(url = "abstract://nano")
[1] 1
> px <- callr::r_bg(function() mirai::dispatcher(client = "abstract://nano", url = "ws://127.0.0.1:57110"))
> px$is_alive()
[1] TRUE
> daemons()
$connections
[1] 0

$daemons
'errorValue' int 5 | Timed out

> px$is_alive()
[1] TRUE
```

**Comment by shikokuchuo** [comment]
oh sorry you need in the first process:
```r
daemons(url = "abstract://nano", dispatcher = FALSE)
```

**Comment by shikokuchuo** [comment]
you are basically manually starting the dispatcher yourself instead of it being launched in a background process. Do you see a 1 `$connections` - you will have just the abstract url at `$daemons` of course.

**Comment by wlandau** [comment]
Looks like it connects without obvious errors:

```r
> library(daemons)
Error in library(daemons) : there is no package called ‘daemons’
> library(mirai)
> daemons(url = "abstract://nano", dispatcher = FALSE)
[1] "abstract://nano"
> px <- callr::r_bg(function() mirai::dispatcher(client = "abstract://nano", url = "ws://127.0.0.1:57111"))
> px$is_alive()
[1] TRUE
> daemons()
$connections
[1] 1

$daemons
[1] "abstract://nano"

> px$get_status()
[1] "sleeping"
```

**Comment by shikokuchuo** [comment]
or on the dispatcher side, and I implemented this specifically for debugging:
```r
mirai::dispatcher(client = "abstract://nano", url = "ws://127.0.0.1:57110",asyncdial=FALSE)
```
You should now get an error such as 6 connection refused if for example the port is closed.

**Comment by shikokuchuo** [comment]
> Looks like it connects without obvious errors:
> 
> ```r
> > library(daemons)
> Error in library(daemons) : there is no package called ‘daemons’
> > library(mirai)
> > daemons(url = "abstract://nano", dispatcher = FALSE)
> [1] "abstract://nano"
> > px <- callr::r_bg(function() mirai::dispatcher(client = "abstract://nano", url = "ws://127.0.0.1:57111"))
> > px$is_alive()
> [1] TRUE
> > daemons()
> $connections
> [1] 1
> 
> $daemons
> [1] "abstract://nano"
> 
> > px$get_status()
> [1] "sleeping"
> ```

Yes, the above looks fine...

**Comment by shikokuchuo** [comment]
Are you getting an issue consistently? Ubuntu has been consistently reliable for me. It really is normally just Windows where things sometimes hang, but usually fine again on a re-run.

**Comment by wlandau** [comment]
On my end, the Windows problems have persisted for several days, so I am skipping those tests on continuous integration. The Ubuntu issues just came up today but have persisted over several runs over the last few hours. The other odd thing is that it only seems to affect R-release and R-oldrel and not R-devel.

**Comment by wlandau** [comment]
And this is what I see with `asyncdial`:

```r
> library(mirai)
> daemons(url = "abstract://nano", dispatcher = FALSE)
[1] "abstract://nano"
> px <- callr::r_bg(function() mirai::dispatcher(client = "abstract://nano", url = "ws://127.0.0.1:57112", asyncdial = FALSE))                                                                                     
> daemons()
$connections
[1] 1

$daemons
[1] "abstract://nano"

> px$is_alive()
[1] TRUE
```

**Comment by shikokuchuo** [comment]
Yes, the status shows you have a connection. If you do `daemons(0)` presumably you should be able to kill the process as well.

I notice the runner is already on R version 4.2.3? I don't even have that yet (it usually takes a couple of days for it to be packaged for Ubuntu). That is something that might have changed over the past few hours...

**Comment by wlandau** [comment]
> Yes, the status shows you have a connection. If you do daemons(0) presumably you should be able to kill the process as well.

Yes, `daemons(0)` does terminate the dispatcher successfully. 

> I notice the runner is already on R version 4.2.3? I don't even have that yet (it usually takes a couple of days for it to be packaged for Ubuntu). That is something that might have changed over the past few hours...

I wonder if that could explain it, or if it affects the tests in `mirai` and/or `nanonext`.

**Comment by shikokuchuo** [comment]
rhub is your answer! maybe try an ubuntu flavour and also `fedora-clang-devel` - that can sometimes catch stuff.

**Comment by shikokuchuo** [comment]
> > I notice the runner is already on R version 4.2.3? I don't even have that yet (it usually takes a couple of days for it to be packaged for Ubuntu). That is something that might have changed over the past few hours...
> 
> I wonder if that could explain it, or if it affects the tests in `mirai` and/or `nanonext`.

I just re-ran the RCMD check workflows for both nanonext and mirai and it is not this. The R version has indeed been updated to 4.2.3 for R-release.

**Comment by shikokuchuo** [comment]
After further investigation I believe I have found it.

After eliminating the impossible, the improbable is all that is left which is that Rscript is not being launched. So oddly enough I was investigating on Windows and the binary install (vs. a source installation) gave me the wrong path for Rscript. I have fixed this by querying the path on load rather than being fixed upon package build.

How does this affect Ubuntu? Digging into the GH run log I find that it downloads from Rstudio (Posit) package manager... and the binary was built this afternoon! Presumably before that it used the source file, which would have worked fine.

I will submit a bug fix version to CRAN  - either requesting manual attention, or else waiting until next week when it will go through automatically.

**Comment by wlandau** [comment]
Thank you for figuring that out. What an elusive issue to diagnose!

I wonder, could `crew` launch the dispatcher manually in a `callr` process? If `crew` runs

```r
daemons(n = 2L, url = "abstract://nano", dispatcher = FALSE)
handle <- callr::r_bg(
  function() mirai::dispatcher(client = "abstract://nano", url = "ws://192.168.0.2:5000", asyncdial = TRUE)
)
```

Is this exactly equivalent to `daemons(n = 2L, url = "ws://192.168.0.2:5000", dispatcher = TRUE)`? Would the dispatcher connect to the client, act just as efficiently as the simpler interface, close workers on exit, and know the right time for itself to exit? Are there any differences in behavior?

Even if this bug were not an issue, a `callr` process would work super well with `crew`, as it would give `crew` more control and information about the dispatcher. I am very keen to pursue this approach on my end. And hopefully it will take pressure off of you in terms of the next release of `mirai`.

**Comment by wlandau** [comment]
And with the `get_start_time()` method of `callr::r_bg()` handlers, it would be no trouble at all to enforce a dispatcher lifespan again on my end.

**Comment by wlandau** [comment]
Hmmm...looks like I can use the active dispatcher that way (I have code that tests against the efficiency of the passive dispatcher) but that workaround is a leaky abstraction. On my local mac, I see:

```r
daemons(n = 2L, url = "ipc://nano", dispatcher = FALSE)
d <- callr::r_bg(
  \() {
    mirai::dispatcher(
      n = 2L,
      client = "ipc://nano",
      url = "ws://127.0.0.1:5001",
      asyncdial = TRUE
    )
  }
)
daemons()
#> $connections
#> [1] 1
#>
#> $daemons
#> [1] "ipc://nano"
```

which means I had to guess at the sockets the dispatcher is using. I could use it if I had to, but then I would need to make assumptions about how `mirai` is defining the websocket paths internally, and I would not get the nice counters and status updates from `daemons()$daemons`. So I no longer like this low-level approach for `crew`.

**Comment by wlandau** [comment]
The relevant code in `callr` seems to be here: https://github.com/r-lib/callr/blob/cd7fe36e4f8b3da97412a8380b492aec2be1f3f1/R/setup.R#L258-L312.

**Comment by wlandau** [comment]
So it looks like:

Executable | OS | `callr` code
---|---|---
R | non-Windows | `file.path(R.home("bin"), "R")`
R | Windows | `file.path(R.home("bin"), "Rterm")` or maybe `file.path(R.home("bin"), "Rterm.exe")`
Rscript | non-Windows | `file.path(R.home("bin"), "Rscript")`
Rscript | Windows | `file.path(R.home("bin"), "Rscript.exe")`

**Comment by shikokuchuo** [comment]
Yes, you have figured out there are still some internal interfaces in `mirai` which are not ideal for you to manipulate directly.

I was in fact aware of such a potential issue (it crossed my mind when we were debugging your SGE cluster - that it might be providing a different Rscript executable to that when the package was built). However it did not cross my mind that this might be the case for a whole *class* of instances... as I never actually use binaries.

This is an example where safety is more important than trying to wring the absolute efficiency, so I now just query and cache on package load. Rest assured, the method of getting the Rscript exec is exactly the same as you detail above for callr. Also `mirai` only uses Rscript, not any of the interactive versions.

The bug is serious enough that I want it fixed straight away, so I will re-submit to CRAN explaining the issue.

I guess you can wait for that to arrive and propagate, or you can use mirai >= 0.8.0 and trust that the new version arrives on CRAN at around the same time.

**Comment by shikokuchuo** [comment]
mirai 0.8.1 pending manual inspection

> Days since last update: 2

**Comment by shikokuchuo** [comment]
> Thanks, on its way to CRAN.
> 
> Best,
> Uwe Ligges 

😄

**Comment by wlandau** [comment]
Fantastic! Looks like those Ubuntu builds are succeeding with `mirai` 0.8.1. Thank you so much!
