### ISSUE TITLE
More Efficient Cleanup 

### ISSUE THREAD

**Issue by shikokuchuo** [wlandau/crew#65]
## Prework

* [x] Read and agree to the [Contributor Code of Conduct](https://github.com/wlandau/crew/blob/main/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/ropensci/crew/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/ropensci/crew/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [ ] Post a [minimal reproducible example](https://www.tidyverse.org/help/) like [this one](https://github.com/ropensci/targets/issues/256#issuecomment-754229683) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [ ] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [ ] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [ ] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

The initial state is obtained and then reset after each task in your crew evaluation wrapper.

Getting the initial state each time is not required.

More efficient solution is to let mirai get this once per daemon and do the cleanup after each task.

1. Remove Global variables
2. Unload packages
3. Reset options
4. Call GC

I know I was not keen on being able to pick and choose, but I am prepared to offer flexibility for each of the above through the cleanup argument being an integer number (operating a bitmask). This will make it too obscure for most users rather than drawing attention to different cleanup options, which was my initial concern.

Are the above the only operations you need?

**Comment by wlandau** [comment]
If you go forward with the bitmask approach for cleanup, I will add logical arguments `garbage_collection` and `unload_packages` to the [`crew` launcher abstract class](https://github.com/wlandau/crew/blob/main/R/crew_launcher.R) and then create the value of the bitmask internally.

**Comment by wlandau** [comment]
I also wonder if you think there may be a faster/native way to restore the RNG state after each task. Currently I am using `withr::local_seed()`, which is robust, but it shows up on the profiling studies. If I could drop it, then it could be a bit of a performance boost, and I could drop the dependency on `withr`.

**Comment by shikokuchuo** [comment]
> If you go forward with the bitmask approach for cleanup, I will add logical arguments `garbage_collection` and `unload_packages` to the [`crew` launcher abstract class](https://github.com/wlandau/crew/blob/main/R/crew_launcher.R) and then create the value of the bitmask internally.

Implemented in mirai 0.8.2.9019. It's a simple additive bitmask, you simply assign the options values 1,2,4,8 and sum them.

I am not entirely sure this works for you as resetting packages without unloading packages could be an issue - `mirai` can only set the options to an initial state before any user packages have been loaded.

Nevertheless, it doesn't hurt to offer the flexibility - there is enough of a disclaimer in the docs.

**Comment by shikokuchuo** [comment]
> I also wonder if you think there may be a faster/native way to restore the RNG state after each task. Currently I am using `withr::local_seed()`, which is robust, but it shows up on the profiling studies. If I could drop it, then it could be a bit of a performance boost, and I could drop the dependency on `withr`.

By restore, do you mean moving the seed to the next one you supply? If you are running stochastic iterations in a `mirai`, you wouldn't want the same RNG state or you'd get the same results each time, unless I'm thinking about something else.

**Comment by shikokuchuo** [comment]
> I also wonder if you think there may be a faster/native way to restore the RNG state after each task. Currently I am using `withr::local_seed()`, which is robust, but it shows up on the profiling studies. If I could drop it, then it could be a bit of a performance boost, and I could drop the dependency on `withr`.

I've had a look at your use of `withr::local_seed()` and I am wondering why you need to reset the RNG state after each eval. Otherwise you would be able to just use `set.seed()`.

The default behaviour of `mirai` is to actually change the RNG state after each eval as it removes `.Random.seed`  as part of the globals cleanup.

**Comment by HenrikBengtsson** [comment]
FYI, be careful when resetting R options.  

There are cases where removing an option wreaks havoc.  For example, in R (< 4.3.0), there were several built-in R options that could not be reset (https://bugs.r-project.org/show_bug.cgi?id=18372).  There are also packages out there that rely on their options not being removed, e.g. <https://github.com/truecluster/ff/issues/14>.

This is why I rolled back automatic setting of R options in **future** a while back (https://github.com/HenrikBengtsson/future/blob/f7c11acb4d2260e882dcd3b392b905c82709d5ae/R/expressions.R#L32-L50) - the risk of breaking things is simply too great.

PS. It feels like I've already mentioned this at some point, but in case I just made that memory up, I'm posting this comment.

**Comment by HenrikBengtsson** [comment]
> I am not sure built-in base options would be affected because the original state should already have the right values, but maybe I am missing something.

Correct, but only since R 4.3.0.

**Comment by shikokuchuo** [comment]
Also just to note on this, options cleanup in `mirai` is light-touch. It only reverts the options that are present at the beginning of the R session. So if a package adds additional options that it relies on, those are actually not removed as part of the cleanup, reducing the chances of breakages in this respect even if the note is not heeded.

The implied assumption is that any new options set by packages would be specific to that package - which again isn't enforceable, but should be true in general - any conflict would be no different to if both namespaces were loaded at the same time, so I contend nothing to be done specifically here.
