### ISSUE TITLE
No need for deep copy of status matrix

### ISSUE THREAD

**Issue by shikokuchuo** [wlandau/crew#72]
## Prework

* [x] Read and agree to the [Contributor Code of Conduct](https://github.com/wlandau/crew/blob/main/CODE_OF_CONDUCT.md) and [contributing guidelines](https://github.com/ropensci/crew/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/ropensci/crew/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [ ] Post a [minimal reproducible example](https://www.tidyverse.org/help/) like [this one](https://github.com/ropensci/targets/issues/256#issuecomment-754229683) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
    * [ ] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [ ] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [ ] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

I just saw this in your recent commit so thought I should mention that there is no need for rlang / full duplicate. I am sure whatever issue it was for has been solved by other means. Also as of mirai 0.8.4, the `daemons()` status matrix is constructed on the client side - it is not sent as an object from dispatcher so there is no possibility of it being anything other than a simple matrix.

```r
rlang::duplicate(
        mirai::daemons(.compute = self$name)$daemons,
        shallow = FALSE
      )
```

**Comment by wlandau** [comment]
Thanks for the FYI, happy to remove calls to `rlang::duplicate()`.
