### ISSUE TITLE
Error in Tutorial for Shiny?

### ISSUE THREAD

**Issue by ekianjo** [wlandau/crew#92]
## Description

The example given your shiny tutorial gives the following error when run:

Error in status_message: attempt to apply non-function

https://wlandau.github.io/crew/articles/shiny.html

**Comment by ekianjo** [comment]
It seems like issue comes from the this line:

reactive_status(status_message(n = [sum](https://rdrr.io/r/base/sum.html)(controller$schedule$summary())))

as in, the schedule object does not appear to exist as expected

**Comment by wlandau** [comment]
`crew` is still a new package, and I needed to refactor it recently: #87. I hope to have the changes on CRAN next week, but for now the app should work if you install the development version using `remotes::install_github("wlandau/crew")`.

**Comment by ekianjo** [comment]
thanks!
